### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by Kriesse** [co-up/co-up.de#1]
In order to make this repository more accessible and open to contribute, the README needs more information, e.g.:

* How to run jekyll locally
* link to jekyll documentation
* ~How to add a blog post~ (done in #4)
* where to find the styleguide
* what kind of help is needed and how to contribute (this could turn into a separate CONTRIBUTE file)

**Comment by mikez** [comment]
I took a stab at the README. See [here](https://github.com/mikez/co-up.de). Thoughts?

__Open questions__:
• Where should people be directed if they have questions involving contribution? An email, join Slack, submit a Github issue?
• What are some first ways (big and small) that people can be offered to contribute?
• Is there a styleguide already somewhere?

**Comment by Kriesse** [comment]
@mikez Great, thanks for taking this on!

- I suggest to direct people with questions to 1) open a github issue if it's directly related to the website, and 2) email to hello@co-up.de for everything else.

- Issues tagged with "good first issue" are a good way to get started https://github.com/co-up/co-up.de/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

- There is a styleguide, https://co-up.de/styleguide/ which needs help:  https://github.com/co-up/co-up.de/issues/10

**Comment by mikez** [comment]
@Kriesse Thanks! I updated it [here](https://github.com/mikez/co-up.de/blob/master/README.md).

**Comment by Kriesse** [comment]
@mikez This is great! Could you open a PR?
