### ISSUE TITLE
Refactor / improve the progress tracker

### ISSUE THREAD

**Issue by Kriesse** [co-up/co-up.de#11]
The progress tracker include could be improved by reducing the hard-coded numbers we have to update.
I.e. it would be nice to only update the absolute numbers, and use JS to calculate the % values.

File: https://github.com/co-up/co-up.de/blob/master/_includes/progress-tracker.html

Current status:
![image](https://user-images.githubusercontent.com/53684/69264294-5030e300-0bc7-11ea-800b-0d5a54368d0d.png)

**Comment by Kriesse** [comment]
Yay, thanks for the improvement, @bastianalbers!
I noticed it stopped working on the FAQ page though https://co-up.de/faq/

**Comment by Kriesse** [comment]
@carmem-s is looking into it

**Comment by bastianalbers** [comment]
Ah, sorry, this is the key https://github.com/co-up/co-up.de/blob/master/support-us.html#L5 
Needs to be on every page that uses this
