### ISSUE TITLE
Create #saveCoUp resources for meetup and event organizers

### ISSUE THREAD

**Issue by saebender** [co-up/co-up.de#16]
We want to provide resources to make it easy for organizers in the space to talk to their members about what co.up needs to survive and make it similarly simple to direct them to become recurring members, contributors, or talk with their employers. What we need:

- [x] Text for organizer mailing groups

- [x] Brochures/flyers to print and put into space

- [x] "Handbook" for organizers

**Comment by saebender** [comment]
Proposed mailing group text: 
You probably know that we use the community space at co.up for our events, and we've got some important news about the space. Their rent will be doubling in 2020 and without immediate financial help they'll be forced to close their doors. It won't just affect us: co.up provides free event space for dozens of community organizations and without a major shift in support they will have to close their doors for good in January 2020. We don't want this to happen!

Here are a few ways you can help #saveCoUp:

- **Become a supporting member of co.up or make a one-time contribution.** Recurring support is vital for their ability to keep co.up open. Go to their [support page for more details.](https://co-up.de/support-us/)
- **Talk to your company about becoming a company supporter.** If your company might be interested in becoming a supporter of co.up, talk to them about the benefits they can offer. For a rundown of what it means to be a co.up company supporter and some common arguments and counters for your conversation, [check out their guide](https://co-up.de/convince-your-company-to-support-coup/).
- **Broadcast your story!** You might have seen some info about co.up and the #saveCoUp campaign online. Everything you can do to share this with your networks will improve their chances of getting enough support. Nothing is as powerful as your personal stories, so if you are comfortable, please tell the world why co.up matters to you!

Still have questions? [They've put together an FAQ](https://co-up.de/faq/) that goes over further details about the space, the campaign, and other things you may not know about co.up. And don't hesitate to reach out to co.up with questions at hello@co-up.de.

**Comment by Kriesse** [comment]
First version is done: https://co-up.de/support-coup-as-organizer/

**Comment by Kriesse** [comment]
Calling this done for now, let's open separate issues for improvements.
