### ISSUE TITLE
Add Company Sponsorship signup buttons in the sponsorship page

### ISSUE THREAD

**Issue by thilo** [co-up/co-up.de#22]
This way we have a direct call to action on that page when people are directed to it.

- [x] agree on sponsorship levels and perks
- [x] create matching plans in Cobot
- [ ] add those plans with direct sign up links on co.up.de

**Comment by Kriesse** [comment]
Good idea! @thilo @CobotClaire How exactly should those plans be called and structured?

**Comment by CobotClaire** [comment]
"co.up Company Supporter X€"?

**Comment by thilo** [comment]
Here my suggestion 
 Activation  | co.up Sponsor 100 | co.up  Sponsor 200 | co.up  Sponsor 400 | co.up  Partner from 500 | 
-- | -- | -- | -- | --
SM Mention | min 1 | min 2 | min 3 | min3 
Website Logo | ✅ | ✅ | ✅ | ✅  
Booking Discount | 10 % | 20 % | 25 % | 30% 
logo space  | ❌ | ✅ | ✅ | ✅  
Sticker table | ❌ | ❌ | ✅  |  ✅  
partner offer co.up | ❌ | ❌ | ❌ | ✅

**Comment by thilo** [comment]
@Kriesse can you add a logo for the 400 Level when you have time
https://members.co-up.de/admin/plans/b402d723bd7f964ce7ff9141943e01c3
