### ISSUE TITLE
Add new Supporter Company logos & links

### ISSUE THREAD

**Issue by CobotClaire** [co-up/co-up.de#26]
Some new company supporters can be added to the main landing page:

- [x] asquera
- [x] Ecosia https://www.dropbox.com/sh/wvhpwyuc7nznnjt/AADjIt6jmOAiAIwdjHjhhfqpa?dl=0
- [x] INNOQ 
- [x] Twilio
- [x] carmunda https://camunda.com/brand  @carmunda
- [x] talent.io  [Logo_talent io-blue](https://user-images.githubusercontent.com/8471/71168156-66799f80-2256-11ea-9bdb-d992312a75d9.jpg)

Ideal image format: 800x360px .svg or .png

**Comment by mikez** [comment]
Should the logos appear in any particular order under "Out Supporters"?

**Comment by CobotClaire** [comment]
I would suggest alphabetically?

**Comment by Kriesse** [comment]
Done thanks to @mikez 👍

**Comment by CobotClaire** [comment]
new logo to add!

-[ ] Twilio

**Comment by thilo** [comment]
Added onemore

**Comment by mikez** [comment]
@thilo added.

**Comment by Kriesse** [comment]
And merged! Once again thank you @mikez 👏

**Comment by thilo** [comment]
And talent.io joned the group too.

**Comment by CobotClaire** [comment]
New logo to add: Port Zero

**Comment by Kriesse** [comment]
@carmem-s Can you add it? Logo and link: https://port-zero.com/

**Comment by thilo** [comment]
all done

**Comment by CobotClaire** [comment]
Could we reorganize the logos alphabetically?
