### ISSUE TITLE
New blog post: December update

### ISSUE THREAD

**Issue by saebender** [co-up/co-up.de#34]
I’ve drafted up a new blog post for today, @Kriesse @CobotClaire can you check it out to make sure I haven’t forgotten anyone or missed some info we want to relay?

# #saveCoUp December Update

We know you’re busy and ready for your holiday break so we won’t take up to much of your time.—there’s just so much good news we wanted to share!

## We’re reached 87%!

All we can say is thank you. There’s no way we’d be at this point without the outpouring of support we’ve received since we began #saveCoUp. Even though we’ve had lots of large donations from companies, the bulk of this support still came from individual donors, which is pretty incredible!

## What’s been happening

Since the info evening, we've had some major donors come through. We’d like to thank all the companies that have agreed to support us so far:

- Asquera
- bitcrowd
- Ecosia
- evenly
- INNOQ
- Neighborhoodie
- Nextjournal
- Twilio

And many thanks to everyone who spoke with their friends and colleagues to get the word out. We’re still talking to a few organizations who might become sponsors in the near future...

## What we’re planning

Before the holidays, we’re preparing materials to start updating the space in the new year. If we can reach our goal, we want to be able to make a few space updates as soon as possible to position the space for a permanent solution. That means making renovations, continuing to build out a base of support, and working on implementing the suggestion we’ve received over the course of the campaign.

Some of the suggestions we’re working on:

- Recruitment events. We want to find an outlet to make both organizers and sponsors happy without compromising the independence of our community and the space.
- More materials for organizers to share with their members.
- Community fundraisers. Ideally we’ll have semi-regular events that can help to support space upkeep and renovation.

If you haven’t become a member yet, it’s not too late! In fact it’s the perfect time, since we’re so close to reaching our goal and there are fewer people for us to reach. See how you can support us at https://co-up.de/support-us/.

## Happy holidays from all of us at co.up - see you next year!

**Comment by Kriesse** [comment]
@saebender Cobot is missing in the company list ;) Other than that, i think it's great and ready to go!

**Comment by saebender** [comment]
@Kriesse haha whoops sorry about that! Fixed :) Here's the final draft to be published. Can you upload it or should I tag someone else?

# #saveCoUp December Update

We know you’re busy and ready for your holiday break so we won’t take up to much of your time.—there’s just so much good news we wanted to share!

## We’re reached 87%!

All we can say is thank you. There is no way we’d be at this point without the outpouring of support we’ve received since we began #saveCoUp. Even though we’ve had lots of large donations from companies, the bulk of this support still came from individual donors, which is pretty incredible!

## What’s been happening

Since the info evening, we've had some major donors come through. We’d like to thank all the companies that have agreed to support us so far:

- [Asquera](https://asquera.de/)
- [bitcrowd](https://bitcrowd.net/)
- [Cobot](https://www.cobot.me/)
- [Ecosia](https://www.ecosia.org/?c=en)
- [evenly](https://evenly.io/)
- [INNOQ](https://www.innoq.com/en/)
- [Neighborhoodie](https://neighbourhood.ie/)
- [Nextjournal](https://nextjournal.com/)
- [Twilio](https://www.twilio.com/)

And many thanks to everyone who spoke with their friends and colleagues to get the word out. We’re still talking to a few organizations who might become sponsors in the near future...

## What we’re planning

Before the holidays, we’re preparing materials to start updating the space in the new year. If we can reach our goal, we want to be able to make a few space updates as soon as possible to position the space for a permanent solution. That means making renovations, continuing to build out a base of support, and working on implementing the suggestion we’ve received over the course of the campaign.

Some of the suggestions we’re working on:

- Recruitment events. We want to find an outlet to make both organizers and sponsors happy without compromising the independence of our community and the space.
- More materials for organizers to share with their members.
- Community fundraisers. Ideally we’ll have semi-regular events that can help to support space upkeep and renovation.

If you haven’t become a member yet, it’s not too late! In fact it’s the perfect time, since we’re so close to reaching our goal and there are fewer people for us to reach. See how you can support us at [https://co-up.de/support-us/](https://co-up.de/support-us/).

## Happy holidays from all of us at co.up - see you next year!

**Comment by Kriesse** [comment]
@saebender I can do it! Ok to publish it right away?

**Comment by saebender** [comment]
Great! I think so, now's our shot to reach people before the holidays so let's really push it

**Comment by Kriesse** [comment]
done: https://co-up.de/2019/12/16/save-coup-december-update/
