### ISSUE TITLE
New landing page for office rental interest

### ISSUE THREAD

**Issue by saebender** [co-up/co-up.de#38]
We plan to announce the need to find a new tenant today, and we want a page on the website to direct any potentially interested parties where they can find more details and information.

- [x] @saebender write copy for website
- [x] @Kriesse create page and add copy

Is there anything else we need to have this page ready? E.x. graphics/buttons/etc?

**Comment by Kriesse** [comment]
@saebender Photos of the office would be great, ideally nice and well-lit… maybe we can reach out to the current tenants and get some / take some?

**Comment by Kriesse** [comment]
@saebender what's a good URL for the page? `/office-for-rent`? 🤔

**Comment by saebender** [comment]
Photos are a good idea, I can also bring my camera tomorrow to take some.

Re: URL, I’d vote: /rent-office or /office-rental

**Comment by saebender** [comment]
Having a lot of trouble with this text, looking for advice on length/key points:

# Your office in the heart of Kreuzberg

Are you searching for an office that is well-connected and offers a furnished, ready-to-go space in one of Berlin's historic industrial buildings? 

Our current tenants are moving out and the space will be available starting on March 1st, 2020. We’re sad to see them go, but excited to see who will move in next.

About the space: You’ll find the office on the third floor of a classic Berlin factory building located directly next to Kottbusser Tor. There is a kitchen and meeting room available to use. The office is located in co.up, a community space that provides affordable event and workshop areas. 

For more information on size, amenities, accessibility, and more, please contact hello@co-up.de. We’d be happy to answer your questions.

**Comment by Kriesse** [comment]
Information needed:
- how many sqm?
- how many seats (= desks) are there, how many people can work there?
- wifi, electricity, heat is included?
- price (do we want to publish it)?
- mention that meetups use the neighboring rooms on some evenings, usually starting between 7-8 pm

**Comment by CobotClaire** [comment]
https://co-up.de/rent-office/
