### ISSUE TITLE
Final #saveCoUp campaign update blog

### ISSUE THREAD

**Issue by saebender** [co-up/co-up.de#43]
Goal is to publish this on the morning of January 10 (instructions in README: https://github.com/co-up/co-up.de#write-and-publish-a-blog-post)

Blog title:  We did it!

# Copy for Blog Post:

We didn’t realize what a roller coaster we were in for when we started our #saveCoUp campaign on November 6th, but as of today, we can safely announce that we will be signing our contract for the next year!

### Let’s take a moment to celebrate—this is an incredible achievement! Thank you!

This would not have been possible without everyone in our community, with a special thanks to all of the company supporters who stepped up to help:

[Asquera](https://asquera.de)

[Bitcrowd](https://bitcrowd.net)

[Camunda](https://camunda.com/)

[Cobot](http://www.cobot.me)

[Ecosia](https://www.ecosia.org/?c=en)

[evenly](https://evenly.io/)

[INNOQ](https://www.innoq.com/en/)

[Neighbourhoodie](https://neighbourhood.ie/)

[Nextjournal](https://nextjournal.com/)

[Port Zero](https://port-zero.com/)

[Talent.io](http://talent.io/)

[Twilio](https://www.twilio.com/)

## What’s next:

During #saveCoUp, we were informed that our long-term back office tenant will be moving out in March. We’re looking for a new tenant to join us, so we’ve set up a page to direct interested companies towards: 

[https://co-up.de/rent-office/](https://co-up.de/rent-office/)

Over the course of the fundraiser, we received many ideas from the community about what they’d like to see from co.up, and some ways to ensure that we'll stay open for years to come. We want to put them into action! We’ll be hosting another info evening where we discuss our path forward and what opportunities this will present for the community.

After we discuss business, but before we get started on that next phase, we want to say thanks and start to give back by hosting a #savedCoUp party! We invite everyone from the co.up community to join us in the space to celebrate this milestone.

### #saveCoUp Info Evening + Party!

January 31st

**19 - 21: Campaign overview**

- Financial situation
- Timeline
- New event info
- Community feedback

**21 - ?: Party** 

- DJ
- Snacks
- Drinks

We hope to see you there!

**Comment by saebender** [comment]
@thilo Does this final update look good to you?

**Comment by Kriesse** [comment]
Approved from my end! 

Help wanted to transform this into a blog post (instructions in README: https://github.com/co-up/co-up.de#write-and-publish-a-blog-post)

**Comment by shushugah** [comment]
> January 31st
> 
> **19 - 21: Campaign overview**
> 
> * Financial situation
> * Timeline
> * New event info
> * Community feedback
> 
> **21 - ?: Party**

The formatting was a bit confusing to me, I would bolden the time, and add `:00` to the times for less ambiguous reading. 

🗓 ### January 31st 

🕖**19:00 -- 21:00**
 * Financial situation
 * Timeline
 * New event info
 * Community feedback
 
 🕘 **21:00 -- ???**
* Party
