### ISSUE TITLE
Updated Support-Us Page

### ISSUE THREAD

**Issue by saebender** [co-up/co-up.de#45]
Now that the #saveCoUp campaign is officially over, the page https://co-up.de/support-us/ should be updated to reflect that we still need donations but that it is no longer part of a time-limited campaign. Here is new draft text for the page:

# Support co.up!

co.up is a community space with a mission—and we rely on your support to continue fighting for better representation in tech.

In order for us to continue offering our space to the community, we need more people to help us financially offset the cost of running co.up. Our goal has always been to help support the independent tech scene in Berlin, and that means that we always offer our space as affordably as possible. Your support will ensure that others have access to these resources going into the future.

Here’s how you can help:

### Become a supporting member

Make a monthly contribution that goes directly into supporting the space and supporting the groups that use it.

[10€ / month](https://members.co-up.de/membership_signup/new?plan_id=ffa4f8bb7f19c0db56c12cd1ed901564)[20€ / month](https://members.co-up.de/membership_signup/new?plan_id=fc3132277c2aa3e38baa11f296bfed97)[50€ / month](https://members.co-up.de/membership_signup/new?plan_id=fdc7bd29643a2454b3339395f0c45673)[100€ / month](https://members.co-up.de/membership_signup/new?plan_id=dcd67ae94d114eeac4739cc148433ea2)[200€ / month](https://members.co-up.de/membership_signup/new?plan_id=dcd67ae94d114eeac4739cc148ea552a)

If you would like to donate a different recurring amount, please [reach out to us](mailto:hello@co-up.de)! We are very open to designing a custom monthly donation and can set that up for you.

### Make a donation

Not ready to become a supporting member yet? Every little bit helps us reach our goal of continuing to offer co.up affordably to community organizations.

[Donate on Ko-Fi](https://ko-fi.com/CoUpCommunity)  [Donate via Paypal](https://www.paypal.me/CoUpCommunity)

### Become a company sponsor

We offer sponsorship packages for companies who would like to support co.up. Read more:

[⭐️ Sponsorships](https://co-up.de/sponsorships)

### Share your co.up story with us

Has an event at co.up changed your life? Helped your career? Made you laugh? We want to hear from you!  [Submit your co.up story »](https://docs.google.com/forms/d/e/1FAIpQLScOkGytFXPTHb1ruQDSGVwa-WxkFOm-TWR2S2753iOkbMoBXA/viewform)

We are very grateful for the support of our amazing community! Reach out to [our team](mailto:hello@co-up.de) if you have questions or want to pay a different amount or in a different way. ❤️

**Comment by CobotClaire** [comment]
I'm open to hearing arguments to the contrary, but my take is that with the campaign concluded, language that implies attaining a (future) goal is not currently necessary and we should stick to language that implies a constant state of relying on outside support.

More concretely I would change these two things:

- In order for us to continue offering our space to the community, we need people _instead of we need more people_

- Every little bit helps us reach our goal of continuing to offer co.up affordably to community organizations _remove "reach our goal" and rewrite the sentence in some way_

**Comment by saebender** [comment]
@CobotClaire I took your suggestions and made a few small tweaks for this draft:

# Support co.up!

co.up is a community space with a mission—and we rely on your support to continue fighting for better representation in tech.

In order for us to offer our space to the community, we need people to help us financially offset the cost of running co.up. Our goal has always been to help support better representation in tech, and that means that we always offer our space as affordably as possible. Your support will ensure that others have access to these resources going into the future.

Here’s how you can help:

### Become a supporting member

Make a monthly contribution that goes directly into supporting the space and supporting the groups that use it.

[10€ / month](https://members.co-up.de/membership_signup/new?plan_id=ffa4f8bb7f19c0db56c12cd1ed901564)[20€ / month](https://members.co-up.de/membership_signup/new?plan_id=fc3132277c2aa3e38baa11f296bfed97)[50€ / month](https://members.co-up.de/membership_signup/new?plan_id=fdc7bd29643a2454b3339395f0c45673)[100€ / month](https://members.co-up.de/membership_signup/new?plan_id=dcd67ae94d114eeac4739cc148433ea2)[200€ / month](https://members.co-up.de/membership_signup/new?plan_id=dcd67ae94d114eeac4739cc148ea552a)

If you would like to donate a different recurring amount, please [reach out to us](mailto:hello@co-up.de)! We are very open to a custom monthly donation and can set that up for you.

### Make a donation

Not ready to become a supporting member yet? No matter how small, your support helps us continue to offer our space affordably to community organizations.

[Donate on Ko-Fi](https://ko-fi.com/CoUpCommunity)  [Donate via Paypal](https://www.paypal.me/CoUpCommunity)

### Become a company sponsor

We offer sponsorship packages for companies who would like to support co.up. Read more:

[⭐️ Sponsorships](https://co-up.de/sponsorships)

### Share your co.up story with us

Has an event at co.up changed your life? Helped your career? Made you laugh? We want to hear from you!  [Submit your co.up story »](https://docs.google.com/forms/d/e/1FAIpQLScOkGytFXPTHb1ruQDSGVwa-WxkFOm-TWR2S2753iOkbMoBXA/viewform)

We are very grateful for the support of our amazing community! Reach out to [our team](mailto:hello@co-up.de) if you have questions or want to pay a different amount or in a different way. ❤️
