### ISSUE TITLE
Add photos of the office to /rent-office

### ISSUE THREAD

**Issue by saebender** [co-up/co-up.de#46]
@Kriesse @CobotClaire In order to make the  page more visually appealing and better showcase the office space itself, we should add a few photos to https://co-up.de/rent-office/

Note: I took many more photos than these, but the ones that include the small lounge ended up looking kind of sad. I’ve included one below the suggested layout in case we’d like to use it. If we want more photos I have more on my computer as well.

This would be the new layout: 

### Office in Kreuzberg for rent starting March 2020

 Are you searching for an office that is well-connected and offers a furnished, ready-to-go space in one of Berlin’s historic industrial buildings? We have a new opening and would love to have you in our space.

### Your office in the heart of Kreuzberg

![P1060587](https://user-images.githubusercontent.com/45603408/72257084-01be2480-360b-11ea-937b-f0a84c15295b.jpg)

Our current tenants are moving out and the office will be available starting on **March 1st, 2020**. We’re sad to see them go, but excited to see who will move in next.

About the space: You’ll find the office on the third floor of a classic Berlin factory building located directly next to Kottbusser Tor. The office is located in co.up, a community space that provides affordable event and workshop areas.

Work next door to startups and companies reshaping the tech industry; in the evenings, the communal space hosts some of Berlin’s most popular tech and creative meetups. Our ideal tenants will enjoy the benefits of working inside a tech community space and can commit to supporting our values and the Code of Conduct.

![P1060584](https://user-images.githubusercontent.com/45603408/72257073-fc60da00-360a-11ea-9519-9b4f15c0086e.jpg)

- Available from March 1st, 2020
- EUR 2200 / month
- Main office room: 42sqm, own lockable door, desks for ca. 7 people available
- Meeting room for ca. 5 people (usage not exclusive, availability might overlap with community events)
- Large event & workshop space (usage not exclusive, availability might overlap with community events)
- Shared kitchen and bathrooms
-  Elevator
- 100 Mbit Internet and Wifi included
- Weekly Cleaning included
- Bike parking available in backyard
- Car parking available upon request (cost not included)

For more information, please contact hello@co-up.de. We’d be happy to answer your questions. ****

---

A few additional photo options:
![P1060580](https://user-images.githubusercontent.com/45603408/72257300-96c11d80-360b-11ea-81c8-de679d5105fc.jpg)

![P1060593](https://user-images.githubusercontent.com/45603408/72257349-bce6bd80-360b-11ea-9f7e-2aba91d8ce37.jpg)

![P1060578](https://user-images.githubusercontent.com/45603408/72257441-f9b2b480-360b-11ea-8945-57d9b301db22.jpg)

![20200113_120404](https://user-images.githubusercontent.com/45603408/72257506-1fd85480-360c-11ea-9139-66d961efa8ce.jpg)

**Comment by CobotClaire** [comment]
Looks good to me - of the remaining photos I would only consider using the bottom one.
