### ISSUE TITLE
update Facebook and Twitter banners

### ISSUE THREAD

**Issue by CobotClaire** [co-up/co-up.de#56]
(The current headers say "#saveCoUp")

**Comment by clairikine** [comment]
asked Clara if she can make some for the end of KW 12 (next week).

**Comment by clairikine** [comment]
Clara currently has no time to take care of this due to covering support. @saebender would this be something you could do bzw. have time for?

**Comment by saebender** [comment]
Sure thing, I can take a swing at it this afternoon @clairikine

**Comment by saebender** [comment]
All done!
