### ISSUE TITLE
Add some links to /support-us and /faq pages

### ISSUE THREAD

**Issue by Kriesse** [co-up/co-up.de#6]
We have written new resources for employees, companies, and meetup organizers on how they can support co.up:

https://co-up.de/sponsorships/
https://co-up.de/convince-your-company-to-support-coup/
https://co-up.de/support-coup-as-organizer/

These links should be added to the /support-us page and to the /faq page.

**Comment by carmem-s** [comment]
@saebender would be god to think where and how to throw in those links.

maybe adding a question on the FAQ about company support?

For now I added a "You can also try to convince your company to support co.up by becoming a sponsor" under "I would like to contribute, but don’t have money."

**Comment by saebender** [comment]
@carmem-s Good idea, I just put together an addition that we can add on the FAQ page, in addition to the part you already added under "I want to contribute, but I don't have money"

Here's the text:
### I want to talk to my company about supporting co.up

That's great! We've put together two resources that you might find helpful.

We have a [guide for talking to your employer](https://co-up.de/convince-your-company-to-support-coup/) that goes through some techniques for convincing them that supporting co.up is a mutually beneficial relationship. It also has a few of the common questions you might receive and some useful answers to know.

And if your company is already interested or needs some more information, we've also put together a [page meant for company representatives](https://co-up.de/sponsorships/) that goes over all the relevant information for company supporters. Feel free to pass on this link to someone in your company responsible for making these decisions.

**Comment by Kriesse** [comment]
closing, it's done!
